export {
  exchangeCodeForToken,
  exchangeForLongLivedToken,
  getAllRelevantEvents,
  getPageEvents,
  getUserPages,
  type FacebookCover,
  type FacebookErrorResponse,
  type FacebookEvent,
  type FacebookPage,
  type FacebookPagePictureData,
  type FacebookPlace,
  type FacebookPlaceLocation,
  setFacebookServiceLogger,
} from "@event-aggregator/shared/services/facebook-service";
